Unit tests for the profile canister.
Psychedelic/dab pull request #12
Opened 2021-08-26 13:14 UTC by Nima-Ra

2021-08-30 06:38 UTC, Nima-Ra commented on profile/src/profile.rs
> +        assert_eq!(profile_db.set_display_name(barry(), String::from("Barry Allen")), ());
True. The Flash is the best lol

2021-08-30 06:59 UTC, Nima-Ra commented
Updated the code to contain the partial and the null case tests.

1. If the requested profile doesn't exist, the expected return value is set to be `None`.

2. If only one of the fields is set (in this case the display name), the only field in the metadata that doesn't have a value of `None` would be the field we set and the version:

```
(
  opt record {
    banner = null;
    description = null;
    emoji = null;
    display_name = opt "Alec Holland";
    version = 0;
    avatar = null;
  },
)
```

2021-08-30 10:35 UTC, kanej requested changes
Can we split into three separate tests.

When a test fails, the name should indicate what the precise problem is to make it an effective regression suite (i.e. you change the default value, and that breaks the api).

2021-08-31 10:53 UTC, Nima-Ra commented
Updated the code. Now each test case is separated from the others.

2021-08-31 10:57 UTC, kanej approved these changes
Thats brilliant. Lets merge this.

2021-08-31 10:58 UTC, merged