NFT canister implementation
Psychedelic/dab pull request #14
Opened 2021-09-06 11:55 UTC by Nima-Ra

This pull request contains the code for the NFT canister implementation with three basic methods: `add`, `remove`, and `get_all`

2021-09-06 13:15 UTC, ferencdg commented on candid/nft.did
> +    "remove" : (text) -> (text);
can we have the return type for the interface methods something like Result<WhateverWeReturn, String> or even better would be something like Result<WhateverWeReturn, (ErrorCode, ErrorString)>

after people start using our dab canister it will be very difficult to change the interface, so the earlier we have a stable interface the better

2021-09-06 13:38 UTC, Nima-Ra commented on candid/nft.did
> +    "remove" : (text) -> (text);
yeah, that's the plan. This is just a very basic version of the canister. They are going to be much cleaner when we introduce them to the community.

2021-09-07 12:07 UTC, ferencdg commented on nft/src/nft.rs
> +impl Default for Registry {
![derive(Default)]
;)

if you are interested we also have code reviews in Dank where similar things occur

2021-09-07 12:09 UTC, ferencdg commented on nft/src/nft.rs
> +        self.0.insert(name, canister_info);
It is difficult to know what self.0 is without scrolling back upwards. In a lot of cases using structs with field names is a better choice than using tuple like structs. 

Tuple like structs are great if the struct is localized like it is only used inside 1 function where you define that struct. If the struct is used throughout your codebase it is better to just have named fields imho.

2021-09-08 14:41 UTC, qti3e requested changes
Can you please use more proper types for the return values?

2021-09-08 14:41 UTC, qti3e commented on nft/src/nft.rs
> +    pub fn add(&mut self, name: String, canister_info: NftCanister) -> String {
Please return `Result<(), String>`

2021-09-08 14:41 UTC, qti3e commented on nft/src/nft.rs
> +    pub fn remove(&mut self, name: &String) -> String {
Again use `Result<(), String>`, client should not compare the result with a string to know the status of failure/success.

2021-09-08 14:41 UTC, qti3e commented on nft/src/nft.rs
> +    ) -> String {
Return `Result<(), String>`

2021-09-08 14:44 UTC, Nima-Ra commented
@qti3e Daniel also asked for that. The return types are going to be changed in another pr for all of the canisters. This pull request is just supposed to add some basic functionality to the canister. I plan on making those changes in the next pull request.

2021-09-08 15:06 UTC, qti3e approved these changes
Okay! So it looks good to me. Thanks for using `ic-kit`.

2021-09-09 08:50 UTC, merged