chore/user_id
Psychedelic/dab pull request #31
Opened 2021-11-03 03:35 UTC by bhflm

2021-11-03 11:11 UTC, Nima-Ra commented on sandbox/profile/src/profile.rs
> +        let user_id = Some(format!("{}#{}",name,rng.gen_range(&MIN_NUMBER_ID..&MAX_NUMBER_ID)));
Do we want the user_id use the same name as the display name field? I personally like to keep my username and display name separate. I think we should manage the username like how Twitter or Telegram does.

2021-11-03 20:14 UTC, Nima-Ra commented on sandbox/profile/src/profile.rs
> +        let user_id = Some(format!("{}#{}",name,rng.gen_range(&MIN_NUMBER_ID..&MAX_NUMBER_ID)));
^ Discussed in Discord

2021-11-09 14:45 UTC, Nima-Ra commented on sandbox/profile/src/profile.rs
> +            true => panic!("Account already exists"),
`panic!` causes the canister to stop functioning. You should return errors using the `Err()` instance.

2021-11-10 15:18 UTC, miguelToscano commented on sandbox/profile/src/profile.rs
> +    if &username.len() < &(*&MAX_USERNAME_LIMIT as usize) && &username.len() > &2 {
isnt `*&` redundant?

2021-11-17 06:50 UTC, Nima-Ra requested changes
Overall it's looking good! A few changes are required though, also I had made one other comment before this review.

2021-11-17 06:50 UTC, Nima-Ra commented on sandbox/profile/src/profile.rs
>      }
line 224 needs to be changed. We should not accept user entries with type `ProfileMetadata` because this struct contains fields that users should not assign like the version field. So another struct is necessary. I dealt with a similar issue in the canister registry so you can check that.

2021-11-17 06:50 UTC, Nima-Ra commented on sandbox/profile/src/profile.rs
> +    pub fn get_user_info(&mut self, user_id: &u32) -> Option<UserInfo> {
the second hashmap was supposed to have have username as key and a vector of user ids as value (if we are doing it sequential then not a vector but just the latest user id)

2021-11-17 06:50 UTC, Nima-Ra commented on sandbox/profile/src/profile.rs
> +        let alice_profile_metadata: ProfileMetadata = ProfileMetadata { user_id: None, username: None, display_name: Some(String::from("Original display name")), description: None, emoji: None, avata
See, user has to pass username, userid and version as nulls and zeros. we need another struct for this.

2021-11-17 12:28 UTC, bhflm commented on sandbox/profile/src/profile.rs
>      }
done

2022-03-28 10:17 UTC, closed without merging