Created tokens registry canister
Psychedelic/dab pull request #34
Opened 2021-12-08 01:44 UTC by miguelToscano

2021-12-10 18:37 UTC, jsonsivar approved these changes
LGTM. Let's leave this PR open until @Nima-Ra reviews and also the README is updated (@miguelToscano @nicolaspoggi ). We will deploy this version and smoke test now.

2021-12-10 18:37 UTC, jsonsivar commented on candid/tokens.did
> +    "set_controller" : (principal) -> (operation_response);
We should add get by canister id/name asap.

2021-12-15 10:02 UTC, Nima-Ra requested changes
Good job! A few changes are needed though.
I think you should run `cargo fmt` as well.

2021-12-15 10:02 UTC, Nima-Ra commented on registries/tokens/src/tokens.rs
> +use ic_cdk::export::candid::{CandidType, Principal};
CandidType and Principal should be imported from ic_kit.

2021-12-15 10:02 UTC, Nima-Ra commented on registries/tokens/src/upgrade.rs
> +use ic_cdk::export::candid::{CandidType, Deserialize, Principal};
CandidType, Deserialize and Principal should be imported from ic_kit.

2021-12-16 14:27 UTC, Nima-Ra approved these changes

2021-12-16 14:27 UTC, merged