Restructuring
Psychedelic/dab pull request #38
Opened 2021-12-30 19:46 UTC by Nima-Ra

2022-02-03 16:55 UTC, qti3e requested changes
i find you guilty of being a NERD xD

2022-02-03 16:55 UTC, qti3e commented on registries/nft/src/nft.rs
> +        Err(OperationError::NonExistentItem)
```suggestion
        if self.0.remove(&principal_id).is_some() {
            return Ok(());
        }

        Err(OperationError::NonExistentItem)
```

2022-02-03 16:55 UTC, qti3e commented on registries/nft/src/nft.rs
>      }
```suggestion
    } else if canister_info.details[0].0 != String::from("standard") {
        return Err(OperationError::BadParameters);
    } else if canister_info.details.len() != 1 {
         return Err(OperationError::BadParameters);
    }
```

2022-02-03 16:55 UTC, qti3e commented on registries/nft/src/upgrade.rs
> +        }
```suggestion
        let updated_nft_canisters = stable.db.into_iter().map(|(_, e)| e.into()).collect();
```

2022-02-03 16:55 UTC, qti3e commented on registries/tokens/src/tokens.rs
> +        || (token.frontend.is_some() && !validate_url(&token.frontend.clone().unwrap()))
```suggestion
        || !token.frontend.map(validate_url).unwrap_or(true)
```

2022-02-03 16:55 UTC, qti3e commented on registries/tokens/src/tokens.rs
> +            && token.details[3].1 != String::from("false"))
DetailValue has `True` and `False` variants

2022-02-03 16:55 UTC, qti3e commented on registries/tokens/src/upgrade.rs
> +                    cs.total_supply.unwrap_or_else(|| 0).to_string(),
use DetailValue::U64

2022-02-03 16:55 UTC, qti3e commented on router/src/router.rs
> +        }
```suggestion
        if self.0.remove(principal_id).is_some() {
            return Ok(());
        }
```

2022-02-03 16:55 UTC, qti3e commented on template_registry/src/registry.rs
> +            || (metadata.frontend.is_some() && !validate_url(metadata.frontend.clone().unwrap()))
```suggestion
            || !metadata.frontend.map(validate_url).unwrap_or(true)
```

2022-02-03 18:09 UTC, Nima-Ra commented on registries/nft/src/upgrade.rs
> +        }
With this code, I have to define the reverse convertion too. (from v1 to v0).

2022-02-03 18:30 UTC, qti3e commented on registries/canister_registry/src/upgrade.rs
> +        for (_key, canister_info) in stable.db.into_iter().enumerate() {
remove the `)`

2022-02-03 18:31 UTC, qti3e commented on registries/nft/src/upgrade.rs
> +        }
no it won't require that, why?

2022-02-03 18:35 UTC, Nima-Ra commented on registries/nft/src/upgrade.rs
> +        }
well, it does.

2022-02-03 18:39 UTC, Nima-Ra commented on registries/canister_registry/src/upgrade.rs
> +        for (_key, canister_info) in stable.db.into_iter().enumerate() {
that's not the issue. `canister_info` will contain both the key and the value of the entry, hence, it is not any different from the code that has been already committed.

2022-02-03 18:39 UTC, Nima-Ra commented on registries/canister_registry/src/registry.rs
> +fn get(canister: Principal) -> Option<&'static CanisterMetadata> {
?

2022-02-07 13:53 UTC, qti3e approved these changes
LGTM

2022-02-07 13:56 UTC, merged