Feature/address book fields
Psychedelic/dab pull request #54
Opened 2022-04-01 10:34 UTC by miguelToscano

2022-04-01 10:35 UTC, miguelToscano commented on registries/address_book/src/address_book.rs
> +    }
this method is a work in progress, im translating https://github.com/Psychedelic/icns-interface/blob/main/utils/utils.ts#L69 into rust

2022-04-04 19:46 UTC, Nima-Ra requested changes

2022-04-04 19:46 UTC, Nima-Ra commented on candid/address_book.did
> +type value_type = variant {
```
value_type = variant {
    PID : principal;
    AccountID : text;
    ICNS : text;
}
```

2022-04-04 19:46 UTC, Nima-Ra commented on candid/address_book.did
> +type address_input = record {
We can remove `address_input`.

2022-04-04 19:46 UTC, Nima-Ra commented on candid/address_book.did
> +    "add"    :  (address: address_input) -> (operation_response);
```suggestion
    "add"    :  (address: address) -> (operation_response);
```

2022-04-04 19:46 UTC, Nima-Ra commented on registries/address_book/src/address_book.rs
> +        let address = Address {
With the proposed changes this will become unnecessary.

2022-04-04 19:46 UTC, Nima-Ra commented on registries/address_book/src/address_book.rs
> +fn add(address: AddressInput) -> Result<(), Failure> {
We should validate all fields in this method.

2022-04-06 05:14 UTC, miguelToscano commented on registries/address_book/src/address_book.rs
> +            crc32fast::hash(&(<[u8; 28]>::from_hex(&account_id.clone()[8..]).unwrap()));
i went insane writing these two lines

2022-04-06 13:35 UTC, Nima-Ra approved these changes
LGTM!

2022-04-06 16:37 UTC, merged